trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Uev/templates/*
    - Uev/tests/*
    - Uev/Publish-Templates.yml

jobs:
- job: push_templates
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    persistCredentials: true

  - task: PowerShell@2
    displayName: "Install Pester"
    inputs:
      targetType: 'inline'
      script: |
        Install-Module -Name "Pester" -Force -Confirm:$False
      verbosePreference: 'SilentlyContinue'
      pwsh: true
      workingDirectory: '$(Build.SourcesDirectory)'

  - task: PowerShell@2
    displayName: "Validate templates against UE-V schema"
    inputs:
      targetType: 'inline'
      script: |
        Import-Module -Name "Pester" -Force
        $Config = [PesterConfiguration]::Default
        $Config.Run.Path = '$(Build.SourcesDirectory)\Uev\tests'
        $Config.Run.PassThru = $True
        $Config.CodeCoverage.Enabled = $False
        $Config.TestResult.Enabled = $True
        $Config.TestResult.OutputFormat = "NUnitXml"
        $Config.TestResult.OutputPath = ".\TestResults.xml"
        Invoke-Pester -Configuration $Config
      verbosePreference: 'SilentlyContinue'
      pwsh: true
      workingDirectory: '$(Build.SourcesDirectory)\Uev\tests'

  - task: AzureFileCopy@4
    displayName: "Push templates to storage account"
    inputs:
      sourcePath: '$(Build.SourcesDirectory)\Uev\templates\*.xml'
      azureSubscription: 'Visual Studio Enterprise Subscription(63e8f660-f6a4-4ac5-ad4e-623268509f20)'
      destination: 'AzureBlob'
      storage: 'stpydeviceause'
      containerName: 'uev'
      additionalArgumentsForBlobCopy: '--log-level=INFO'
